#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""make_config.py —— 把一个 .pcrec 的 header JSON 抽成 flat key=value 配置文件。

用法：
    python tools/pcrec/make_config.py recordings/xxx.pcrec out/config.txt

给 C++ 离线重放器(front_replay.cpp)用：C++ 侧不需要 JSON 解析，
所有标定/模板/参数快照都摊平成一行的 key=value。
"""
import sys, os, json
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
import pcrec as P

def flat_calib(r):
    cams = P.calib(r)
    out = {}
    out["ncams"] = len(cams)
    for c in cams:
        i = c.get("idx", 0)
        out[f"cam.{i}.fx"] = c.get("fx", 0.0)
        out[f"cam.{i}.fy"] = c.get("fy", 0.0)
        out[f"cam.{i}.cx"] = c.get("cx", 0.0)
        out[f"cam.{i}.cy"] = c.get("cy", 0.0)
        out[f"cam.{i}.k1"] = c.get("k1", 0.0)
        out[f"cam.{i}.k2"] = c.get("k2", 0.0)
        out[f"cam.{i}.k3"] = c.get("k3", 0.0)
        out[f"cam.{i}.p1"] = c.get("p1", 0.0)
        out[f"cam.{i}.p2"] = c.get("p2", 0.0)
        R = c.get("R", [1,0,0,0,1,0,0,0,1])
        t = c.get("t", [0,0,0])
        for k in range(9): out[f"cam.{i}.R.{k}"] = R[k]
        for k in range(3): out[f"cam.{i}.t.{k}"] = t[k]
    return out

def main():
    src, dst = sys.argv[1], sys.argv[2]
    r = P.load(src)
    h = r.header if isinstance(r.header, dict) else json.loads(r.header)
    lines = []
    lines.append(f"# generated by make_config.py from {os.path.basename(src)}")
    lines.append(f"protocol={h.get('protocol','')}")
    lines.append(f"recorderVersion={h.get('recorderVersion', 0)}")

    # template
    tpl = h.get("template", {})
    lines.append(f"isRight={1 if tpl.get('isRight') else 0}")
    bm = tpl.get("backMarkers", [])
    for k, v in enumerate(bm):
        lines.append(f"back.{k}={v}")
    fp = tpl.get("fingerParams", [])
    for f, o in enumerate(fp):
        a = o.get("anchor", [0,0,0]); L = o.get("lengths",[0,0,0])
        for k in range(3):
            lines.append(f"finger.{f}.anchor.{k}={a[k]}")
            lines.append(f"finger.{f}.lengths.{k}={L[k]}")
        lines.append(f"finger.{f}.dipCoupling={o.get('dipCoupling',0.7)}")

    # calibration
    for k, v in flat_calib(r).items():
        lines.append(f"{k}={v}")

    # params snapshot (flat)
    params = h.get("params", {})
    for k, v in params.items():
        if isinstance(v, bool):
            lines.append(f"{k}={1 if v else 0}")
        elif isinstance(v, (int, float)):
            lines.append(f"{k}={v}")
        else:
            lines.append(f"{k}={v}")

    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {dst}  {len(lines)} lines")

if __name__ == "__main__":
    main()
